[profile.default]
src = "src"
out = "out"
libs = ["lib"]

gas_reports = ["*"]
no_test = true


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"
ethereum = "${ETHEREUM_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }


[fmt] # See https://book.getfoundry.sh/reference/config/formatter
int_types = "short"
line_length = 120
bracket_spacing = true
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "single"
ignore = ['./script/**/*']

[fuzz]
runs = 10000
seed = "1234"
dictionary_weight = 100


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
