[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc = "0.8.28"

gas_reports = ["*"]
no_test = true
evm_version = "shanghai"


[rpc_endpoints]
sepolia = "${SEPOLIA_RPC_URL}"

[etherscan]
sepolia = { key = "${ETHERSCAN_API_KEY}" }

[fuzz]
runs = 10000
seed = "1234"
dictionary_weight = 100
fail_on_revert = true


[invariant]
runs = 1000
depth = 1000
fail_on_revert = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
